# Generated by Django 5.2 on 2025-04-20 16:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_conditionazpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionpage',
            name='also_known_as_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Also Known As (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='causes_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Causes (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='diagnosis_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Diagnosis (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='overview_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Overview (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='prevention_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Prevention (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='symptoms_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Symptoms (Hindi)'),
        ),
        migrations.AddField(
            model_name='conditionpage',
            name='treatments_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Treatments (Hindi)'),
        ),
    ]
