# Generated by Django 5.2 on 2025-04-20 15:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAZPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drug A-Z Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drug Category',
                'verbose_name_plural': 'Drug Categories',
            },
        ),
        migrations.CreateModel(
            name='DrugIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drug Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DrugPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('brand_names', models.CharField(blank=True, max_length=255)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('overview', wagtail.fields.RichTextField()),
                ('uses', wagtail.fields.RichTextField()),
                ('dosage', wagtail.fields.RichTextField()),
                ('side_effects', wagtail.fields.RichTextField()),
                ('warnings', wagtail.fields.RichTextField()),
                ('interactions', wagtail.fields.RichTextField(blank=True)),
                ('storage', wagtail.fields.RichTextField(blank=True)),
                ('pregnancy_category', models.CharField(blank=True, max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='drugs', to='drugs.drugcategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Drug Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
