# Generated by Django 5.2 on 2025-04-20 16:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlepagetag_articlepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='body_hi',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Body (Hindi)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Hindi)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='summary_hi',
            field=models.TextField(blank=True, verbose_name='Summary (Hindi)'),
        ),
    ]
