# Generated by Django 5.2 on 2025-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlepage_body_hi_articlepage_subtitle_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='slug_hi',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug (Hindi)'),
        ),
    ]
